apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classification
  template:
    metadata:
      labels:
        app: image-classification
    spec:
      containers:
      - name: image-classification
        image: tin2294/image-classification:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /test
            port: 5000
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 3
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
