name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u tin2294 --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/tin2294/image-classification:latest .

    - name: Push Docker Image
      run: |
        docker push ghcr.io/tin2294/image-classification:latest

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .


    - name: Run main.py
      run: python main.py
      working-directory: .

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q