name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        description: "0.0.1"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: node-0

    steps:
      - name: Deploy application
        run: |
          docker build -t node-0:5000/ml-app:latest app
          docker push node-0:5000/ml-app:latest

          kubectl apply -f ~/image-classification-continuous-x/deploy_k8s/deployment_k8s.yaml

      - name: Display Docker Logs
        run: |
            docker logs $(docker ps -q -f ancestor=node-0:5000/ml-app:latest) || echo "No Docker container running for ml-app"
    
      - name: Display Kubernetes Pod Status
        run: |
          kubectl get pods -o wide || echo "Kubernetes pod status not available"

      - name: Display Kubernetes URL
        run: |
          echo http://$(curl -s ifconfig.me/ip):32000