name: Redeploy on New Model Update

on:
  push:
    branches:
      - main
  # commented out to force trigger
    # paths:
    #     - "app/model.keras"

jobs:
  redeploy:
    runs-on: self-hosted
    name: Redeploy ML App

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Registry
      run: |
        echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u tin2294 --password-stdin

    - name: Build and push Docker image
      run: |
          docker build -t node-0:5000/ml-app:latest app
          docker push node-0:5000/ml-app:latest

    - name: Apply Kubernetes manifest
      run: |
          kubectl apply -f ~/image-classification-continuous-x/deploy_k8s/deployment_k8s.yaml

    - name: Display Docker Logs
      run: |
        docker logs $(docker ps -q -f ancestor=node-0:5000/ml-app:latest) || echo "No Docker container running for ml-app"

    - name: Display Kubernetes Pod Status
      run: |
        kubectl get pods -o wide || echo "Kubernetes pod status not available"

    - name: Display Kubernetes URL
      run: |
        echo http://$(curl -s ifconfig.me/ip):32000
