name: Redeploy on New Model Update

# on:
#   push:
#     branches:
#       - main
#     # paths:
#     #     - "app/model.keras"
on:
  push:
    tags:
      - redeploy

jobs:
  redeploy:
    runs-on: [self-hosted, node-0]
    name: Redeploy ML App

    steps:
    - name: Get Latest Model
      id: get_latest_model
      run: |
        LATEST_MODEL=$(ls -Art saved_model/*.h5 | tail -n 1)
        echo "Latest model path: $LATEST_MODEL"
        echo "LATEST_MODEL=$LATEST_MODEL" >> $GITHUB_ENV

    # GET THE FRONT END PART WITH LATEST SOFTWARE
    # NEED TO GET THE LATEST MODEL
    - name: Build and push Docker image
      run: |
          docker build -t node-0:5000/ml-app:latest app
          docker push node-0:5000/ml-app:latest

    # Make sure it is actually redeploying (non disrupting) - currently not redeploying if deploying
    - name: Apply Kubernetes manifest
      run: |
          kubectl apply -f ~/image-classification-continuous-x/deploy_k8s/deployment_k8s.yaml

    - name: Display Docker Logs
      run: |
        docker logs $(docker ps -q -f ancestor=node-0:5000/ml-app:latest) || echo "No Docker container running for ml-app"

    - name: Display Kubernetes Pod Status
      run: |
        kubectl get pods -o wide || echo "Kubernetes pod status not available"

    - name: Display Kubernetes URL
      run: |
        echo http://$(curl -s ifconfig.me/ip):32000
