name: Train Model

on:
  push:
    branches:
      - main
    paths:
      - 'model_train.py'

jobs:
  train-evaluate:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          mkdir -p content/Food-11
          gdown https://drive.google.com/uc?id=1dt3CD3ICdLbTf80sNJ25TPBDKu_qyCnq -O content/Food-11/dataset.zip
          unzip content/Food-11/dataset.zip -d content/Food-11
        working-directory: .

      - name: Run Training Script
        run: |
          python model_train.py

      - name: Display Evaluation Results
        run: |
          cat evaluation_metrics.txt || echo "Evaluation metrics not available"

      - name: Parse Evaluation Metrics
        id: metrics
        run: |
          evaluation_accuracy=$(grep 'evaluation_accuracy' evaluation_metrics.txt | cut -d' ' -f2)
          echo "::set-output name=evaluation_accuracy::$evaluation_accuracy"

      - name: Redeploy if Accuracy Meets Threshold
        if: steps.metrics.outputs.evaluation_accuracy >= 0.90
        run: |
          git tag -a "redeploy" -m "Auto-redeploy from training workflow"
          git push origin redeploy
